### ISSUE TITLE
Message when there is no available route

### ISSUE THREAD

**Issue by jpvguerreiro** [hulop/NavCogIOSv3#43]
When there is no route available, the system does not inform the user.

In some cases, it is because the route options are to not using the elevator or stairs, but the only path is through the elevator or stairs, respectively.

**Comment by itohtaka** [comment]
Do you mean ``There is no route for the specified conditions. `` message in MapService?
https://github.com/hulop/MapService/blob/master/MapService/WebContent/messages/en.json#L26
If that is the issue, do you have any alternative message?
"conditions" includes many items not only stair and elevator.
- Minimum width
- Slope
- Road surface condition
- Step
- Stairs
- Escalator
- Moving walkway
- Elevator

**Comment by daisukes** [comment]
Thank you for your comment @itohtaka san.

This issue is for NavCog blind user mode. At least it should provide like "no route found." Moreover, if the system can provide a message telling that there is a route with the "default" setting for the blind user mode, it may be useful.

I don't think MapService needs an update for this issue.

**Comment by jpvguerreiro** [comment]
Thanks @itohtaka.

Yes, sorry for not specifying that it was the Blind user mode.. when I tried it did not provide any message in that mode (it just returns to the previous menu).
