### ISSUE TITLE
carthage build error

### ISSUE THREAD

**Issue by daisukes** [hulop/NavCogIOSv3#53]
carthage build failed with errors. I got the same error with #51.

I have tried to fix the issue with the [workaround script](https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md) but it did not work, which looked working in July somehow with my environment.

Then, I made a new branch to try to use "swift package" version of HLPDialog.
https://github.com/hulop/NavCogIOSv3/tree/fix-carthage-build-error

I could launch the app, but I don't have time to check if the app is correctly working.

**Comment by hiroshi-shin** [comment]
In order to use the layouts created in Swift, I have created an `Objective-C Bridging Heading`.

However, when I tried to include any class that uses `HLPDialog`, I got an error saying that
> Module 'HLPDialog' not found

The Brigding [Header](https://github.com/miraikan-research/NavCogIOSv3/blob/miraikan-build-error/Miraikan/NavCog3-Bridging-Header.h#:~:text=%23import%20%22BlindViewController.h%22)
The ViewController [Header](https://github.com/miraikan-research/NavCogIOSv3/blob/miraikan-build-error/NavCog3/BlindViewController.h#:~:text=%40import-,HLPDialog,-%3B)

In addition, I also got an error 
> Cannot find protocol declaration for 'WKNavigationDelegate'

when implementing some `UIView` with `WkNavigationDelegate`

The [UIView](https://github.com/miraikan-research/NavCogIOSv3/blob/miraikan-build-error/Miraikan/Contents/ExhibitionView.swift#:~:text=WKNavigationDelegate) which implements the delegate.

I guess that I missed some settings for Swift integration.

**Comment by daisukes** [comment]
Hello @hiroshi-shin 

Thank you for trying to utilize the HULOP code!
Next time, could you please create a new issue to ask this kind of question?

I could fix your issues.

>> Module 'HLPDialog' not found
>
> The Brigding Header

This is because that the objective-c bridging header imports a swift package, which creates a cyclic reference.
So you need to make a forward declaration instead of importing the swift package.
Fortunately, it just refers to `DialogViewDelegate`
https://stackoverflow.com/a/44756250/15421301

```
//@import HLPDialog;

@protocol DialogViewDelegate
- (void) dialogViewTapped;
@end
```

> > Cannot find protocol declaration for 'WKNavigationDelegate'
> 
> when implementing some `UIView` with `WkNavigationDelegate`

This can be fixed by adding an include statement in AppDelegate.h

```
 #import <UIKit/UIKit.h>
 #import <CoreBluetooth/CoreBluetooth.h>
 #import <HLPLocationManager/HLPLocationManager.h>
+#import <WebKit/WebKit.h>
 #import <NavCog3-Swift.h>
```

In addition, it would be better to fix NavCog3-Bridging-Header.h

```
 #ifndef NavCog3_Bridging_Header_h
 #define NavCog3_Bridging_Header_h
 
-
-#endif /* NavCog3_Bridging_Header_h */
-
 #import "BlindViewController.h"
 #import "HLPSettingHelper.h"
 #import "ServerConfig.h"
+
+#endif /* NavCog3_Bridging_Header_h */
```

**Comment by hiroshi-shin** [comment]
@daisukes 
Thank you very much for teaching me those advanced technologies.
I will create a new issue the next time.
